package com.silence5105.nosy.partner2go;

/**
 * Created by Nosy on 2017/1/24.
 */

public enum  PreferenceKeys {
    KMKEY,MAIL,AUTOLOGIN,CARCLASS
    ,STARTADDRESS,ENDADDRESS,STARTLOCATION,ENDLOCATION,STEPS,PUSHKEY,REGIID
    ,HAVED
    ,CLIENTTIME
    ,ORDERID
    ,MENUCOST
    ,PAYMENTTYPE
    ,HAVEKEY
    ,PHONENUMBER
    ,HTIME
    ,ALLTIME
    ,CLIENTORDERID
    ,OFFICIALTYPE
    ,DRIVERNAME
    ,COST
    ,OFFICIALBOOKING
    ,DRIVERRATE
    ,GOTIME
    ,DRIVERPHONENUMBER
    ,TEXTNUMBER
    ,DRIVERCARCLASS
    ,DRIVERLAT
    ,DRIVERLNG
    ,STARTLAT
    ,STARTLNG
    ,ENDLAT
    ,ENDLNG
    ,DRIVEROTW
    ,OFFICIALCARCLASS
    ,LISTSELECT
    ,LAST30M
    ,LAST5M
    ,ORDERTYPE
    ,USERNAME
}
